// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYZT1dllpqQtrcTADCYpJ0yeWCM2LVNGA',
    appId: '1:451138456437:web:9fd651b177d8afc2bd613c',
    messagingSenderId: '451138456437',
    projectId: 'dalili-9206a',
    authDomain: 'dalili-9206a.firebaseapp.com',
    storageBucket: 'dalili-9206a.firebasestorage.app',
    measurementId: 'G-0SHC6L4B1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8yq2LJ1ZfhCY5ykBtEBZWV2XRagf6fFo',
    appId: '1:451138456437:android:4d1be399a4d4b673bd613c',
    messagingSenderId: '451138456437',
    projectId: 'dalili-9206a',
    storageBucket: 'dalili-9206a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzsdHt6h6B-o_CJtMpNkYw1B8GBFa2M6I',
    appId: '1:451138456437:ios:97d83b1f5619e614bd613c',
    messagingSenderId: '451138456437',
    projectId: 'dalili-9206a',
    storageBucket: 'dalili-9206a.firebasestorage.app',
    iosBundleId: 'com.example.serviceFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzsdHt6h6B-o_CJtMpNkYw1B8GBFa2M6I',
    appId: '1:451138456437:ios:97d83b1f5619e614bd613c',
    messagingSenderId: '451138456437',
    projectId: 'dalili-9206a',
    storageBucket: 'dalili-9206a.firebasestorage.app',
    iosBundleId: 'com.example.serviceFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYZT1dllpqQtrcTADCYpJ0yeWCM2LVNGA',
    appId: '1:451138456437:web:530dbb7d758cb6fdbd613c',
    messagingSenderId: '451138456437',
    projectId: 'dalili-9206a',
    authDomain: 'dalili-9206a.firebaseapp.com',
    storageBucket: 'dalili-9206a.firebasestorage.app',
    measurementId: 'G-JCWJP8ZG5K',
  );
}
